version: "3.9"

networks:
  default:
    driver: bridge

services:
  backend:
    image: backend
    ports:
      - "8080:8080"
    networks:
      - default

  frontend:
    image: frontend
    build: .
    ports:
      - "4200:4200"
    networks:
      - default